### ISSUE TITLE
verifyProof should load public keys with JSON LD resolution

### ISSUE THREAD

**Issue by humayunj** [zkp-ld/jsonld-proofs#14]
`verifyProof` requires publicKeys doc to be passed separately but it could be auto fetched as JSONLD document with `proof.verificationMethod`
```
export const verifyProof = async (
  vp: jsonld.JsonLdDocument,
  publicKeys: jsonld.JsonLdDocument,
  documentLoader: DocumentLoader,
  options?: VerifyProofOptions,
): Promise<VerifyResult> 
```

If there's a single issuer or single credential, we can easily pass the publicKeys by manually fetching but when multiple credentials are included in the proof with different issuers it complicates external publicKeys document. 

I can work on a PR if given some direction. (like whether this should be handled at JS level or Rust level)

**Comment by yamdan** [comment]
Hi @humayunj, thank you for your suggestion! I agree that the auto-fetching of issuer public keys is a useful feature. This library is still in its early stages and has limited functionality for key management and remote file referencing. We would greatly welcome a PR if possible😄  Here are some points to consider when adding the automatic key retrieval feature:

- **Implementation of a DID resolver**: Selecting the appropriate DID methods to support. Initially, I think it would be good to incorporate simple third-party resolvers like `did:key` and `did:web`.
- **Choosing between `jsonld-proofs` (TS/JS) and `rdf-proofs` (Rust)**: Since processing JSON-LD documents is necessary, I believe `jsonld-proofs` (TS/JS level) is more suitable.
- **Relationship with `jsonld.js`'s `documentLoader`**: Deciding whether the `documentLoader` should focus solely on resolving JSON-LD contexts or be extended to also handle DID resolution.
- **Security and privacy issues** related to retrieving remote documents.

**Comment by humayunj** [comment]
Thanks @yamdan. I'll prepare a PR soon.

**Comment by gertjandemulder** [comment]
+1
